//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SsmsLogin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SsmsLogin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ssms.
        /// </summary>
        internal static string ProcessSsmsExeName {
            get {
                return ResourceManager.GetString("ProcessSsmsExeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files (x86)\Microsoft SQL Server Management Studio 19\Common7\IDE\Ssms.exe.
        /// </summary>
        internal static string ProcessSsmsExePath {
            get {
                return ResourceManager.GetString("ProcessSsmsExePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to Server.
        /// </summary>
        internal static string ProcessSsmsLoginWindowTitle {
            get {
                return ResourceManager.GetString("ProcessSsmsLoginWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entry must have a password..
        /// </summary>
        internal static string UiErrorEntryNoPassword {
            get {
                return ResourceManager.GetString("UiErrorEntryNoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entry must have a string entry ssms_server that contains the target server name.
        ///This is the &quot;Data Source&quot;, &quot;Server&quot;, &quot;Address&quot;, &quot;Addr&quot;, or &quot;Network Address&quot; from the connection string..
        /// </summary>
        internal static string UiErrorEntryNoServer {
            get {
                return ResourceManager.GetString("UiErrorEntryNoServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entry must have a user name..
        /// </summary>
        internal static string UiErrorEntryNoUsername {
            get {
                return ResourceManager.GetString("UiErrorEntryNoUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open SSMS.
        /// </summary>
        internal static string UiOpenSsms {
            get {
                return ResourceManager.GetString("UiOpenSsms", resourceCulture);
            }
        }
    }
}
